using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KaiSeki;

public partial class WordPage : ContentPage
{
    public WordPage(Word word)
    {
        InitializeComponent();
        
        Title = word.Kanji;
        //set the word
        Kanji.Text = word.Kanji;
        Hiragana.Text = word.Hiragana;
        //text generated by gemini, example paragraph
        // if(word.Gemini == "") Gemini.Text = "面倒事が嫌いだから逆らいはしないものの、トワ自身は生活を改める気など全くなかった。";
        // else Gemini.Text = word.Gemini;
    }
}